### ISSUE TITLE
Inclusions Error on Particle Photon

### ISSUE THREAD

**Issue by chixxi** [dnrce/Particle-PID#3]
Hi Dan

First off, a huge thank you for providing this library. I want to use this for a beer fermentor temperature controller.

I have a pretty basic problem with the library: I have added the library to my project, but the line "#include <pid.h>" gives this error: pid.h: No such file or directory

Do you have any hints why this could be happening? I also tried your examples, there the inclusion seems to work fine.

I am using firmware 0.7.0 on the particle.

**Comment by dnrce** [comment]
Hi @chixxi! I deserve very little credit -- I'm only adapting an already useful library for Particle.

Pretty hard to say from here. How did you add the library? Was it via the "Libraries" page in the Particle IDE? You might have more luck troubleshooting in https://community.particle.io/.

I'm going to close this but feel free to open a new issue if you uncover anything that's a problem with the library itself. Thanks!

**Comment by chixxi** [comment]
Thanks for your quick answer!

I used the official way to add the library, meaning I used it on https://build.particle.io/build/ and included it over the web interface. I am also using other libraries like OneWire.h which were included successfully.

Well, I found a way around the issue: I opened your examples, saved it as a new project and I went ahead from there. So I am happy now.
